#############################################################################
# Makefile for building: ModbusIO
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  ModbusIO.pro
# Template: app
# Command: /home/jto/Qt5.6.2/5.6/gcc_64/bin/qmake -o Makefile ModbusIO.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.6.2/5.6/gcc_64/include -I../../Qt5.6.2/5.6/gcc_64/include/QtGui -I../../Qt5.6.2/5.6/gcc_64/include/QtCore -I. -I../../Qt5.6.2/5.6/gcc_64/mkspecs/linux-g++
QMAKE         = /home/jto/Qt5.6.2/5.6/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ModbusIO1.0.0
DISTDIR = /home/jto/Projects/modbusio/.tmp/ModbusIO1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/jto/Qt5.6.2/5.6/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/jto/Qt5.6.2/5.6/gcc_64/lib -lQt5Gui -L/usr/lib64 -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = modbusprotocol.cpp \
		modbuspacket.cpp \
		modbusmodule.cpp \
		modulehandler.cpp \
		modbusmasterioprivate.cpp \
		readholdingregisterspacket.cpp \
		writemultipleregisterspacket.cpp \
		readwritemultipleregisterspacket.cpp \
		readcoilspacket.cpp \
		writemultiplecoilspacket.cpp \
		digitalnetconverttracker.cpp \
		modbusslaveioserver.cpp \
		modbusslaveioprivate.cpp \
		modbusmasterioserver.cpp \
		modbusiobuilder.cpp 
OBJECTS       = modbusprotocol.o \
		modbuspacket.o \
		modbusmodule.o \
		modulehandler.o \
		modbusmasterioprivate.o \
		readholdingregisterspacket.o \
		writemultipleregisterspacket.o \
		readwritemultipleregisterspacket.o \
		readcoilspacket.o \
		writemultiplecoilspacket.o \
		digitalnetconverttracker.o \
		modbusslaveioserver.o \
		modbusslaveioprivate.o \
		modbusmasterioserver.o \
		modbusiobuilder.o
DIST          = ModbusIO.xml \
		QDoc/examples/001_io_config.xml \
		QDoc/examples/002_protocol.xml \
		QDoc/examples/003_transport.xml \
		QDoc/examples/004_tcp_transport.xml \
		QDoc/examples/005_serial_transport.xml \
		QDoc/examples/006_node.xml \
		QDoc/examples/007_packet_1.xml \
		QDoc/examples/008_packet_2.xml \
		QDoc/examples/009_modbusslaveioserver.xml \
		QDoc/examples/010_io_config_master.xml \
		QDoc/examples/011_protocol_master.xml \
		QDoc/examples/012_transport_master.xml \
		QDoc/examples/013_tcp_transport_master.xml \
		QDoc/examples/014_node_master.xml \
		QDoc/examples/015_packet_1_master.xml \
		QDoc/examples/016_packetelement_master.xml \
		QDoc/examples/017_modbusmasterioserver.xml \
		QDoc/examples/018_console_demo.xml \
		Templates/Models/IOModule.xml \
		Templates/Models/ModbusIO.1-AI-short.xml \
		Templates/Models/ModbusIO.1-AO-short.xml \
		Templates/Models/ModbusIO.1-DI.xml \
		Templates/Models/ModbusIO.1-DO.xml \
		Templates/Models/ModbusIO.16-DI.xml \
		Templates/Models/ModbusIO.16-DO.xml \
		Templates/Models/ModbusIO.2-AI-short.xml \
		Templates/Models/ModbusIO.2-AO-short.xml \
		Templates/Models/ModbusIO.2-DI.xml \
		Templates/Models/ModbusIO.2-DO.xml \
		Templates/Models/ModbusIO.4-AI-short.xml \
		Templates/Models/ModbusIO.4-AO-short.xml \
		Templates/Models/ModbusIO.4-DI.xml \
		Templates/Models/ModbusIO.4-DO.xml \
		Templates/Models/ModbusIO.8-AI-short.xml \
		Templates/Models/ModbusIO.8-AO-short.xml \
		Templates/Models/ModbusIO.8-DI.xml \
		Templates/Models/ModbusIO.8-DO.xml \
		Templates/Models/ModbusIO.ModbusMasterPacket.xml \
		Templates/Models/ModbusIO.ModbusMasterRTU.xml \
		Templates/Models/ModbusIO.ModbusMasterTCP.xml \
		Templates/Models/ModbusIO.ModbusMasterUDP.xml \
		Templates/Models/ModbusIO.ModbusSlavePacket.xml \
		Templates/Models/ModbusIO.ModbusSlaveRTU.xml \
		Templates/Models/ModbusIO.ModbusSlaveTCP.xml \
		Templates/Models/ModbusIO.ModbusSlaveUDP.xml \
		Templates/Models/ModbusIO.Phoenix-AXL-F-BK-ETH-UDP.xml \
		Templates/Models/ModbusIO.Wago-750-UDP.xml \
		Templates/Models/ModbusIO.Weidmueller-UR20-FBC-MOD.xml \
		Test/ComponentTest/TestLib/TestLib.xml \
		Test/ComponentTest/TestConfigurations/MODBUSTCP_AlignOnByteBoundary/Components/ModbusMasterTCP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSTCP_AlignOnByteBoundary/Components/ModbusSlaveTCP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSTCP_AlignOnByteBoundary/Components/ModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSTCP_AlignOnByteBoundary/Models/CDPModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignAdjacent/Components/ModbusMasterUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignAdjacent/Components/ModbusSlaveUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignAdjacent/Components/ModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignAdjacent/Models/CDPModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignOnByteBoundary/Components/ModbusMasterUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignOnByteBoundary/Components/ModbusSlaveUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignOnByteBoundary/Components/ModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignOnByteBoundary/Models/CDPModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignOnWordBoundary/Components/ModbusMasterUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignOnWordBoundary/Components/ModbusSlaveUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignOnWordBoundary/Components/ModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_AlignOnWordBoundary/Models/CDPModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadCoils_AOWB/Components/ModbusMasterUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadCoils_AOWB/Components/ModbusSlaveUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadCoils_AOWB/Components/ModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadCoils_AOWB/Models/CDPModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadHolding_AA/Components/ModbusMasterUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadHolding_AA/Components/ModbusSlaveUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadHolding_AA/Components/ModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadHolding_AA/Models/CDPModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadWriteMultiple_AOWB/Components/ModbusMasterUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadWriteMultiple_AOWB/Components/ModbusSlaveUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadWriteMultiple_AOWB/Components/ModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_ReadWriteMultiple_AOWB/Models/CDPModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_WriteCoils_AOWB/Components/ModbusMasterUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_WriteCoils_AOWB/Components/ModbusSlaveUDP.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_WriteCoils_AOWB/Components/ModbusTester.xml \
		Test/ComponentTest/TestConfigurations/MODBUSUDP_WriteCoils_AOWB/Models/CDPModbusTester.xml \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/lex.prf \
		ModbusIO.pro modbusio.h \
		modbusiobuilder.h \
		modbusslaveioserver.h \
		modbusmasterioserver.h \
		modbusslaveudp.h \
		modbusslavetcp.h \
		modbusslavertu.h \
		modbusmasterudp.h \
		modbusmastertcp.h \
		modbusmasterrtu.h \
		modbusprotocol.h \
		modbuspacket.h \
		modbusmodule.h \
		modulehandler.h \
		modbusmasterioprivate.h \
		readholdingregisterspacket.h \
		writemultipleregisterspacket.h \
		readwritemultipleregisterspacket.h \
		readcoilspacket.h \
		writemultiplecoilspacket.h \
		digitalnetconverttracker.h \
		modbusslaveioprivate.h modbusprotocol.cpp \
		modbuspacket.cpp \
		modbusmodule.cpp \
		modulehandler.cpp \
		modbusmasterioprivate.cpp \
		readholdingregisterspacket.cpp \
		writemultipleregisterspacket.cpp \
		readwritemultipleregisterspacket.cpp \
		readcoilspacket.cpp \
		writemultiplecoilspacket.cpp \
		digitalnetconverttracker.cpp \
		modbusslaveioserver.cpp \
		modbusslaveioprivate.cpp \
		modbusmasterioserver.cpp \
		modbusiobuilder.cpp
QMAKE_TARGET  = ModbusIO
DESTDIR       = 
TARGET        = ModbusIO


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ModbusIO.pro ../../Qt5.6.2/5.6/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt5.6.2/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.6.2/5.6/gcc_64/mkspecs/features/lex.prf \
		ModbusIO.pro \
		../../Qt5.6.2/5.6/gcc_64/lib/libQt5Gui.prl \
		../../Qt5.6.2/5.6/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ModbusIO.pro
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/common/unix.conf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/common/linux.conf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/common/sanitize.conf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/common/g++-base.conf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/qconfig.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/qt_config.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/spec_post.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/default_pre.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/default_post.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/warn_on.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/qt.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/resources.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/moc.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/file_copies.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/exceptions.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/yacc.prf:
../../Qt5.6.2/5.6/gcc_64/mkspecs/features/lex.prf:
ModbusIO.pro:
../../Qt5.6.2/5.6/gcc_64/lib/libQt5Gui.prl:
../../Qt5.6.2/5.6/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ModbusIO.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents modbusio.h modbusiobuilder.h modbusslaveioserver.h modbusmasterioserver.h modbusslaveudp.h modbusslavetcp.h modbusslavertu.h modbusmasterudp.h modbusmastertcp.h modbusmasterrtu.h modbusprotocol.h modbuspacket.h modbusmodule.h modulehandler.h modbusmasterioprivate.h readholdingregisterspacket.h writemultipleregisterspacket.h readwritemultipleregisterspacket.h readcoilspacket.h writemultiplecoilspacket.h digitalnetconverttracker.h modbusslaveioprivate.h $(DISTDIR)/
	$(COPY_FILE) --parents modbusprotocol.cpp modbuspacket.cpp modbusmodule.cpp modulehandler.cpp modbusmasterioprivate.cpp readholdingregisterspacket.cpp writemultipleregisterspacket.cpp readwritemultipleregisterspacket.cpp readcoilspacket.cpp writemultiplecoilspacket.cpp digitalnetconverttracker.cpp modbusslaveioserver.cpp modbusslaveioprivate.cpp modbusmasterioserver.cpp modbusiobuilder.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

modbusprotocol.o: modbusprotocol.cpp modbusprotocol.h \
		modbuspacket.h \
		modulehandler.h \
		digitalnetconverttracker.h \
		readholdingregisterspacket.h \
		writemultipleregisterspacket.h \
		readwritemultipleregisterspacket.h \
		readcoilspacket.h \
		writemultiplecoilspacket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusprotocol.o modbusprotocol.cpp

modbuspacket.o: modbuspacket.cpp modbuspacket.h \
		modulehandler.h \
		digitalnetconverttracker.h \
		modbusmodule.h \
		modbusprotocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbuspacket.o modbuspacket.cpp

modbusmodule.o: modbusmodule.cpp modbusmodule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusmodule.o modbusmodule.cpp

modulehandler.o: modulehandler.cpp modulehandler.h \
		digitalnetconverttracker.h \
		modbusmodule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modulehandler.o modulehandler.cpp

modbusmasterioprivate.o: modbusmasterioprivate.cpp modbusmasterioprivate.h \
		modbusmasterioserver.h \
		modbuspacket.h \
		modulehandler.h \
		digitalnetconverttracker.h \
		modbusprotocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusmasterioprivate.o modbusmasterioprivate.cpp

readholdingregisterspacket.o: readholdingregisterspacket.cpp readholdingregisterspacket.h \
		modbuspacket.h \
		modulehandler.h \
		digitalnetconverttracker.h \
		modbusprotocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readholdingregisterspacket.o readholdingregisterspacket.cpp

writemultipleregisterspacket.o: writemultipleregisterspacket.cpp writemultipleregisterspacket.h \
		modbuspacket.h \
		modulehandler.h \
		digitalnetconverttracker.h \
		modbusprotocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o writemultipleregisterspacket.o writemultipleregisterspacket.cpp

readwritemultipleregisterspacket.o: readwritemultipleregisterspacket.cpp readwritemultipleregisterspacket.h \
		modbuspacket.h \
		modulehandler.h \
		digitalnetconverttracker.h \
		modbusprotocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readwritemultipleregisterspacket.o readwritemultipleregisterspacket.cpp

readcoilspacket.o: readcoilspacket.cpp readcoilspacket.h \
		modbuspacket.h \
		modulehandler.h \
		digitalnetconverttracker.h \
		modbusprotocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readcoilspacket.o readcoilspacket.cpp

writemultiplecoilspacket.o: writemultiplecoilspacket.cpp writemultiplecoilspacket.h \
		modbuspacket.h \
		modulehandler.h \
		digitalnetconverttracker.h \
		modbusprotocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o writemultiplecoilspacket.o writemultiplecoilspacket.cpp

digitalnetconverttracker.o: digitalnetconverttracker.cpp digitalnetconverttracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o digitalnetconverttracker.o digitalnetconverttracker.cpp

modbusslaveioserver.o: modbusslaveioserver.cpp modbusslaveioserver.h \
		modbusslaveioprivate.h \
		modbuspacket.h \
		modulehandler.h \
		digitalnetconverttracker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusslaveioserver.o modbusslaveioserver.cpp

modbusslaveioprivate.o: modbusslaveioprivate.cpp modbusslaveioprivate.h \
		modbuspacket.h \
		modulehandler.h \
		digitalnetconverttracker.h \
		modbusslaveioserver.h \
		modbusprotocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusslaveioprivate.o modbusslaveioprivate.cpp

modbusmasterioserver.o: modbusmasterioserver.cpp modbusmasterioserver.h \
		modbusmasterioprivate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusmasterioserver.o modbusmasterioserver.cpp

modbusiobuilder.o: modbusiobuilder.cpp modbusiobuilder.h \
		modbusmasterudp.h \
		modbusmasterioserver.h \
		modbusmastertcp.h \
		modbusmasterrtu.h \
		modbusslaveudp.h \
		modbusslaveioserver.h \
		modbusslavetcp.h \
		modbusslavertu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusiobuilder.o modbusiobuilder.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

